### ISSUE TITLE
Som besökare vill jag kunna urskilja länkar

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/terapirekommendationer.se#23]
@regionhallandviktor commented on [Wed Mar 21 2018](https://github.com/RegionHalland/vardgivarwebben/issues/41)

## Acceptanskriterier
- [ ] Länkar är tydligt urskiljbara se Stilguiden i wikin

Övrigt: Den nuvarande länkfärgen har bara en kontrast på 2.17:1 vilket gör dem svåra att upptäcka för de med dåligt färgseende eftersom färg är den enda betydelsebäraren. 

---

@regionhallandviktor commented on [Mon Apr 16 2018](https://github.com/RegionHalland/vardgivarwebben/issues/41#issuecomment-381556416)

Se t.ex. http://stage-vardgivare.regionhalland.se/service-it/it-stod-och-system/lakemedelsdatabas-pillan/ där det idag (16 april 2018) är i princip omöjligt att urskilja länken som inleder texten på sidan.

**Comment by viktor-sarge** [comment]
Hm. Ligger i terapirek och där tror jag inte något är gjort, men exemplet är från vgw där det är bättre (om än inte färdigt). Tycker vi stänger den och gör nya för specifika situationer istället.
