### ISSUE TITLE
Fel författare visas i versionshanteringen

### ISSUE THREAD

**Issue by JohannaOlin** [RegionHalland/terapirekommendationer.se#25]
I versionslistan för sidan http://vardgivare.regionhalland.se/terapirek/terapirekommendationer/kapitel12/rekommenderade-lakemedel/ så står det bland annat att Agneta.Ljunggren och alf.svensson har gjort nya versioner, men det har de inte.

Kan det ha blivit något fel när Terapirekommendationerna flyttades?

**Comment by davidohlin** [comment]
Har inte kommit fram till någon lösning här och kan inte återskapa problemet. Har kollat med Anton om det kan vara så att användarna har använt en delad dator och glömt logga in / ut. 

Wordpress versionshantering är inte modifierad av oss och jag har ganska mycket tillit till den. Lämnar detta tills vidare så får vi se om det uppstår igen.

**Comment by JohannaOlin** [comment]
Vi stänger denna så får vi skapa en ny issue om vi får fler indikationer på att något verkligen är fel.
